<?php
/** @var  $block  \Magenest\Movie\Block\Button */
?>

<div class="actions">
    <button type="button">Custome Button</button>
    <button type="button">Open Magento Login Modal</button>
    <button type="button">Open Customer Login Modal</button>
</div>
<!--<div>-->
<!--    <a class="primary action" href="">--><?//= __('Open Modal') ?><!--</a>-->
<!--    <a class="primary action" href="">--><?//= __('Open Magento Login Modal') ?><!--</a>-->
<!--    <a class="primary action" href="">--><?//= __('Open Customer Login Modal') ?><!--</a>-->
<!--</div>-->
<!--<script>-->
<!--    require(["jquery","Magenest_Movie/js/customalert"], function (custom){-->
<!--        alert(custom.getText());-->
<!--    });-->
<!--</script>-->
